import React from "react";

const Recommendations = ({ recommendations = [] }) => {
    return (
        <div className="bg-[#171C34] border border-white/10 rounded-xl p-5">
            {/* Header */}
            <div className="flex items-center justify-between mb-6">
                <div>
                    <h2 className="text-xl font-semibold">
                        AI Recommendations
                    </h2>

                    <p className="text-gray-400 text-sm mt-1">
                        Suggested improvements generated by AI.
                    </p>
                </div>

                <span className="bg-emerald-500/20 text-emerald-300 px-4 py-2 rounded-lg text-sm">
                    {recommendations.length} Suggestions
                </span>
            </div>

            {recommendations.length ? (
                <div className="space-y-4">
                    {recommendations.map((item, index) => (
                        <div
                            key={index}
                            className="bg-[#0F172A] border border-white/10 hover:border-emerald-500/40 rounded-xl p-5 transition-all"
                        >
                            <div className="flex justify-between items-start gap-4">
                                <div className="flex gap-4">
                                    <div className="h-12 w-12 rounded-xl bg-emerald-500/20 flex items-center justify-center text-emerald-300 font-bold">
                                        {index + 1}
                                    </div>

                                    <div>
                                        <h3 className="text-lg font-semibold text-white">
                                            {item.title}
                                        </h3>

                                        <div className="mt-2">
                                            <span
                                                className={`px-3 py-1 rounded-full text-xs font-medium ${item.priority === "High"
                                                    ? "bg-red-500/20 text-red-300"
                                                    : item.priority ===
                                                        "Medium"
                                                        ? "bg-yellow-500/20 text-yellow-300"
                                                        : "bg-emerald-500/20 text-emerald-300"
                                                    }`}
                                            >
                                                {item.priority} Priority
                                            </span>
                                        </div>
                                    </div>
                                </div>

                                <i className="bi bi-lightbulb-fill text-yellow-400 text-2xl"></i>
                            </div>

                            {/* Recommendation */}
                            <div className="mt-5 bg-emerald-500/10 border border-emerald-500/20 rounded-lg p-4">
                                <div className="flex items-center gap-2 mb-2">
                                    <i className="bi bi-stars text-emerald-400"></i>

                                    <h4 className="font-semibold text-emerald-300">
                                        Recommendation
                                    </h4>
                                </div>

                                <p className="text-gray-300 leading-7">
                                    {item.recommendation}
                                </p>
                            </div>

                            {/* Reason */}
                            <div className="mt-4 bg-[#171C34] rounded-lg p-4 border border-white/5">
                                <div className="flex items-center gap-2 mb-2">
                                    <i className="bi bi-info-circle text-sky-400"></i>

                                    <h4 className="font-semibold text-sky-300">
                                        Why AI Suggested This
                                    </h4>
                                </div>

                                <p className="text-gray-400 leading-7">
                                    {item.reason}
                                </p>
                            </div>
                        </div>
                    ))}
                </div>
            ) : (
                <div className="py-16 text-center">
                    <div className="h-20 w-20 rounded-full bg-emerald-500/20 flex items-center justify-center mx-auto">
                        <i className="bi bi-check-circle-fill text-5xl text-emerald-400"></i>
                    </div>

                    <h3 className="text-2xl font-semibold mt-6">
                        No Recommendations
                    </h3>

                    <p className="text-gray-400 mt-3">
                        AI didn't find any improvements for this contract.
                    </p>
                </div>
            )}
        </div>
    );
};

export default Recommendations;